_HiStOrY_V2_
importurllib2
req=urllib2.Request('http://www.webscription.net/10.1125/Baen/0671578456/0671578456___8.htm')
con=urllib2.urlopen(req)
con
html=con.read()
html
importBeautifulSoup
ls
soup=BeautifulSoup(html)
soup=BeautifulSoup.BeautifulSoup(html)
soup
printsoup.prettify()
soup.p
pTag=soup.p
pTag.contents
pTag.contents[1].contents
soup.head.nextsibling.name
soup.head.nextSibling.name
soup.p.nextSibling.name
soup.p
soup.p.next
p=soup.p.next
p
p=soup.p.next
p
p.next
p=p.next
p
p=p.next
p
p=p.next;p
soup.findAll('p')
soup.findAll(lambdatag:len(tag.attrs)==2)
soup.findAll(lambdatag:len(tag.attrs)==2andtag.name=='p')
soup.findAll(lambdatag:len(tag.attrs)==2andtag=='p')
soup.findAll(lambdatag:len(tag.attrs)==2andtag.name=='p')
soup.findAll(lambdatag:len(tag.attrs)==2andtag.name=="p")
soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=="p")
soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p')
soup.findAll(lambdatag:len(tag.attrs)is1andtag.nameis'p'andtag.nameisnot'a')
soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p'andtag.name!='a')
soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p').prettify()
soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p')
soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p')[1]
soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p')[13]
len(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p'))
fromrandomimportchoice
choice(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p'))
choice(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p')).split()
split(choice(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p')))
choice(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p')).split()
choice(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p'))
choice(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p')).__type__
str(choice(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p'))).split()
choice(str(choice(soup.findAll(lambdatag:len(tag.attrs)==1andtag.name=='p'))).split())
importreadline
readline.write_history_file('using_bs.py')
